## How to read an Image from data path 

### Setup the Jupyter Notebook and Install the Libraries

In [1]:
# Import libraries
import cv2
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
#Checking the Data Path for Image read
import os
imagePath = "data/images/number_zero.jpg"
print(os.path.exists(imagePath))  # Should return True

True


In [4]:
#Reading Image from custom data path
imagePath = ("data/images/number_zero.jpg")
# Read image in format 0: Grayscale ,1:RGB,-1:Unchanged
testImage = cv2.imread(imagePath,0)
print(testImage)

[[  1   0   3   0   3   0   3   2   4   2   0]
 [  0   1   0   3   3 253 253   0   0   2   1]
 [  0   0   8   0 249 255 255 253  71   1   5]
 [  3   0   2 251 255   2   0 253 254   0   2]
 [  1   5   0 252   4   0   3   0 255   4   0]
 [  0   0   2 255   0   0   0   3 253   0   4]
 [  0   5   4 249   4   2   0   0 255   1   0]
 [  2   0   0 255   3   0   5   0 254   0   4]
 [  0   0   0 255   1   0   0   3 255   0   0]
 [  1   5   0 252   2   2   2  76 250   7   0]
 [  0   0   5   0 254   0   0 255 254   0   1]
 [  0   8   0   3 253 253 255 250   1   2   1]
 [  2   0   0   0   5   0   4   1   3   0   0]]


In [5]:
#Defining base Data path and creating Image
data_path = ("data/images/")
imagePath = os.path.join(data_path,"number_zero.jpg")
print(os.path.exists(imagePath))  # Should return True

True


In [6]:
# Reading Image for Image path
data_path = ("data/")
imagePath = os.path.join(data_path,"images/number_zero.jpg")

# Read image in Grayscale format
testImage = cv2.imread(imagePath,0)
print(testImage)

[[  1   0   3   0   3   0   3   2   4   2   0]
 [  0   1   0   3   3 253 253   0   0   2   1]
 [  0   0   8   0 249 255 255 253  71   1   5]
 [  3   0   2 251 255   2   0 253 254   0   2]
 [  1   5   0 252   4   0   3   0 255   4   0]
 [  0   0   2 255   0   0   0   3 253   0   4]
 [  0   5   4 249   4   2   0   0 255   1   0]
 [  2   0   0 255   3   0   5   0 254   0   4]
 [  0   0   0 255   1   0   0   3 255   0   0]
 [  1   5   0 252   2   2   2  76 250   7   0]
 [  0   0   5   0 254   0   0 255 254   0   1]
 [  0   8   0   3 253 253 255 250   1   2   1]
 [  2   0   0   0   5   0   4   1   3   0   0]]


In [7]:
print("Data type = {}\n".format(testImage.dtype))
print("Object type = {}\n".format(type(testImage)))
print("Image Dimensions = {}\n".format(testImage.shape))
# The size or resolution is 13x11 which means height=13 and witdh=11. In other words, it has 13 rows and 11 columns.

Data type = uint8

Object type = <class 'numpy.ndarray'>

Image Dimensions = (13, 11)

